language: node_js

node_js:
    - "11"
    - "10"
    - "9"

services: redis-server

env:
    - REDIS_DSN=redis://localhost:6379

sudo: false
if: tag IS blank

branches:
    only:
        - master

install:
    - npm i

script:
    - npm run test
    - npm run build

after_success:
    - npm run coverage
    - npm i -g semantic-release@15 @semantic-release/npm @semantic-release/changelog @semantic-release/git @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/release-notes-generator
    - npx semantic-release
