language: node_js
matrix:
    include:
        -   node_js: 11
        -   node_js: 10
            env: COVERAGE=true
        -   node_js: 19

sudo: false
services: redis-server
install:
    - npm i

stages:
    - name: test
      if: branch = master AND tag IS blank
    - name: release
      if: branch = master AND tag IS blank

script: npm run test && if [[ "$COVERAGE" = "true" ]]; then npm run coverage; fi

jobs:
    include:
        -   stage: release
            node_js: 10
            script: |
                npm run build
                npm i -g semantic-release@15 @semantic-release/npm @semantic-release/changelog @semantic-release/git @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/release-notes-generator
                npx semantic-release
